### ISSUE TITLE
I think this should be added to man page

### ISSUE THREAD

**Issue by dm-s** [uprt/labean#2]
Config file in example show how to setup nginx to work with labean.
But for noobies like me, it's difficult to setup apache2 to work with labean.

I spent some time to write config file for apache2 servers. 

Maybe for someone my work will be helpfull

This part you should paste into your apache2 config file

<Location ~ "/secret/(.*)">
        RewriteEngine on
        Options +FollowSymlinks
        AllowOverride All
        deny from all
        AuthType basic
        AuthName "Administrator login"
        AuthUserFile /etc/apache2/htpasswd
        Satisfy Any
        Require valid-user
        header add  X-Real-IP "%{REMOTE_ADDR}s"
        RequestHeader append X-Real-IP "%{REMOTE_ADDR}s"
        ProxyPass http://127.0.0.1:8080/$1
</Location>

maybe this config made not quite competently, but it works

**Comment by noiseonwires** [comment]
Thank you for your proposal.
Actually, web server config examples in this repo are not in the README/manpage, but in a dedicated 'examples' directory.
Could you make a pull request with your config in there?
