### ISSUE TITLE
No such task

### ISSUE THREAD

**Issue by mkll** [uprt/labean#4]
If we specify the secret URL as shown in the doc (`https://someserver.org/secret/vpn/on`), we get the "No such task" error.

So, we should use `https://someserver.org/secret/secret/vpn/on` instead to make things working. :)

P.S. Tried to change `http://127.0.0.1:8080/$1` to `http://127.0.0.1:8080$request_uri`, but got "500 Internal Server Error" due to, I think, leading slash in the URI that can't be handled by labean.

Another fix: set `http://127.0.0.1:880/secret/$1` in the nginx config.

**Comment by noiseonwires** [comment]
Seems I was not clear enough in the manual. `url_prefix` in the configuration must be set only if your reverse proxy (e.g. nginx) can't rewrite URLs. In that case, you set `url_prefix` to your secret URL and  labean will trim it by itself.
If your reverse-proxy is already configured to trim this prefix (as it is done in the `examples` folder of the repo), then in labean's configuration it should be set empty.
