### ISSUE TITLE
 "allow_explicit_ips": true, seems not working

### ISSUE THREAD

**Issue by carboncool** [uprt/labean#5]
I use "allow_explicit_ips": true, and with nginx example reverse proxy  config , but seems the use of https://someserver.org/secret/service/on/?ip=123.56.78.9 not working, the clientIp isn't ip address 123.56.78.9 .  The clientIp is still the real client IP  but not specified  ?ip=123.56.78.9 .
Or maybe I config nor using it wrong . 
Need your help. 
Thank you very much!
By the way , if there is a client app on android or ios etc, will be even greater I wish.

**Comment by noiseonwires** [comment]
I tested again (without nginx) and it works for me.
However, seems like there's a mistake in Nginx config example.

If you are using the config from this repo, could you please try to use `proxy_pass http://127.0.0.1:8080/$1$is_args$args` or `proxy_pass http://127.0.0.1:8080/$1?$query_string` instead of `proxy_pass http://127.0.0.1:8080/$1` and check if it works well?

**Comment by noiseonwires** [comment]
And about mobile app, the idea of https knocking is that no additional apps are required, even from the mobile device you can knock using browser (e.g. add shortcuts for the specific URLs).
We can do some PWA (progressive webapp) that will expose tasks list in a nice-looking way and perform corresponding API calls, but I don thave such plans for now

**Comment by carboncool** [comment]
> 

Thank you very much ! It does  caused by the nginx reverse config, after I  follow your suguestion proxy_pass http://127.0.0.1:8080/$1$is_args$args , it works fine,  you helped me a lot, very thankful !

**Comment by carboncool** [comment]
> And about mobile app, the idea of https knocking is that no additional apps are required, even from the mobile device you can knock using browser (e.g. add shortcuts for the specific URLs). We can do some PWA (progressive webapp) that will expose tasks list in a nice-looking way and perform corresponding API calls, but I don thave such plans for now

You are right , thank you very much for the very helpful app. It is just what I need.
